FROM python:3.8-slim-buster

WORKDIR /app

COPY ./backend/requirements.txt requirements.txt

RUN apt-get update

RUN apt-get install libpq-dev python-dev -y

RUN apt-get install libjpeg-dev zlib1g-dev gcc -y

RUN pip install psycopg2-binary

RUN apt-get install graphviz graphviz-dev -y

RUN pip3 install -r requirements.txt

COPY ./backend/. .
ENV SECRET_KEY '15+n96&r%)n47of%6f(5#mjh2y)syma#n^1+=qp+3larhra=vn'
CMD python3 manage.py runserver 0.0.0.0:8000
